"""Move is_active column from profiles table to users table

Revision ID: acafa9e5c5c2
Revises: fd2529170436
Create Date: 2022-07-04 10:22:34.199299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "acafa9e5c5c2"
down_revision = "fd2529170436"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profiles", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
