"""create_sections_table

Revision ID: 2e0adbb52685
Revises: 24fed9555ab8
Create Date: 2022-07-09 14:00:23.338784

"""
from alembic import op
import sqlalchemy as sa

from database.migrations.data.sections import sections_seed


# revision identifiers, used by Alembic.
revision = "2e0adbb52685"
down_revision = "24fed9555ab8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sections = op.create_table(
        "sections",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "content_type",
            sa.Enum("lesson", "quiz", "assignment", name="contenttype"),
            nullable=False,
        ),
        sa.Column("grade_media", sa.SmallInteger(), nullable=True),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.bulk_insert(sections, sections_seed)

    op.create_index(op.f("ix_sections_id"), "sections", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sections_id"), table_name="sections")
    op.drop_table("sections")
    # ### end Alembic commands ###
